<a href="https://colab.research.google.com/github/3B032007/2025_ML_hws/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業1 模擬多隱藏層的全連接神經網路

## 1、定義各個激發函數

In [ ]:
import numpy as np
# sigmoid激發函數
def sigmoid(x):
    return 1/(1+np.exp(-x))

# ReLU激發函數
def relu(x):
    return np.maximum(0, x)

#Softmax函數
def softmax(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

## 2、設定輸入層的6個神經元

In [ ]:
x=np.array([-1.0, 1.0, 2.0, 3.0, 4.0, 5.0])

print(x.shape)

(6,)


## 3、第一層隱藏層5個神經元

In [ ]:
W1=np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
      [0.2, 0.3, 0.4, 0.5, 0.6],
      [0.3, 0.4, 0.5, 0.6, 0.7],
      [0.7, 0.6, 0.5, 0.4, 0.3],
      [0.6, 0.5, 0.4, 0.3, 0.2],
      [0.5, 0.4, 0.3, 0.2, 0.1]])
b1=np.array([0.1, 0.2, 0.3, 0.4, 0.5])

print(W1.shape)
print(b1.shape)

# 計算加權和z1及輸出量h1 激發函數使用ReLU
z1=np.dot(x,W1)+b1
h1=relu(z1)
print(h1)

(6, 5)
(5,)
[7.8 6.9 6.  5.1 4.2]


## 4、第二層隱藏層4個神經元

In [ ]:
W2=np.array([[0.1, 0.3, 0.5, 0.7],
      [0.2, 0.4, 0.6, 0.8],
      [0.3, 0.5, 0.7, 0.9],
      [0.4, 0.6, 0.8, 0.1],
      [0.5, 0.7, 0.9, 0.3]])
b2=np.array([0.1, 0.2, 0.3, 0.4])

print(W2.shape)
print(b2.shape)

# 計算加權和z2及輸出量h2 激發函數使用ReLU
z2=np.dot(h1,W2)+b2
h2=relu(z2)
print(h2)

(5, 4)
(4,)
[ 8.2  14.3  20.4  18.55]


## 5、第三層隱藏層4個神經元

In [ ]:
W3=np.array([[0.7, 0.6, 0.4, 0.3],
      [0.4, 0.2, 0.1, 0.7],
      [0.8, 0.4, 0.3, 0.5],
      [0.1, 0.6, 0.9, 0.3]])
b3=np.array([0.1, 0.2, 0.3, 0.4])

print(W3.shape)
print(b3.shape)

# 計算加權和z3及輸出量h3 激發函數使用sigmoid
z3=np.dot(h2,W3)+b3
h3=sigmoid(z3)
print(h3)

[1. 1. 1. 1.]


## 6、輸出層3個神經元

In [ ]:
W4=np.array([[0.3, 0.9, 0.4],
      [0.2, 0.1, 0.6],
      [0.6, 0.8, 0.5],
      [0.7, 0.4, 0.9]])
b4=np.array([0.1, 0.2, 0.3])

print(W4.shape)
print(b4.shape)

# 計算輸出結果 激發函數使用softmax
z4=np.dot(h3,W4)+b4
y_hat=softmax(z4)
print(y_hat)

(4, 3)
(3,)
[0.20515925 0.33825043 0.45659032]


## 7、利用cross_entropy_error衡量y_hat與y之間的誤差值

In [ ]:
def cross_entropy_error(y_hat, y):
    return -np.sum(y * np.log(y_hat + 1e-7))

In [ ]:
y=[0, 0, 1]

In [ ]:
np.log(y_hat + 1e-7)

array([-1.58396826, -1.08396845, -0.78396853])

In [ ]:
np.log(y_hat + 1e-7)

array([-1.58396826, -1.08396845, -0.78396853])

In [ ]:
y*np.log(y_hat + 1e-7)

array([-0.        , -0.        , -0.78396853])

In [ ]:
-np.sum(y * np.log(y_hat + 1e-7))

np.float64(0.7839685302264483)

In [ ]:
cross_entropy_error(y_hat, y)

np.float64(0.7839685302264483)

# 引用gradio套件

In [ ]:
pip install gradio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.2/322.2 kB 26.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 61.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 6.9 MB/s eta 0:00:00


In [ ]:
import numpy as np
import gradio as gr

In [ ]:
# sigmoid激發函數
def sigmoid(x):
    return 1/(1+np.exp(-x))

# ReLU激發函數
def relu(x):
    return np.maximum(0, x)

#Softmax函數
def softmax(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

# 定義dnn函數
def dnn(x):
  # 第一層隱藏層
  W1=np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
        [0.2, 0.3, 0.4, 0.5, 0.6],
        [0.3, 0.4, 0.5, 0.6, 0.7],
        [0.7, 0.6, 0.5, 0.4, 0.3],
        [0.6, 0.5, 0.4, 0.3, 0.2],
        [0.5, 0.4, 0.3, 0.2, 0.1]])
  b1=np.array([0.1, 0.2, 0.3, 0.4, 0.5])
  z1=np.dot(x,W1)+b1
  h1=relu(z1)

  # 第二層隱藏層
  W2=np.array([[0.1, 0.3, 0.5, 0.7],
        [0.2, 0.4, 0.6, 0.8],
        [0.3, 0.5, 0.7, 0.9],
        [0.4, 0.6, 0.8, 0.1],
        [0.5, 0.7, 0.9, 0.3]])
  b2=np.array([0.1, 0.2, 0.3, 0.4])
  z2=np.dot(h1,W2)+b2
  h2=relu(z2)

  # 第三層隱藏層
  W3=np.array([[0.7, 0.6, 0.4, 0.3],
        [0.4, 0.2, 0.1, 0.7],
        [0.8, 0.4, 0.3, 0.5],
        [0.1, 0.6, 0.9, 0.3]])
  b3=np.array([0.1, 0.2, 0.3, 0.4])
  z3=np.dot(h2,W3)+b3
  h3=sigmoid(z3)

  # 輸出層
  W4=np.array([[0.3, 0.9, 0.4],
        [0.2, 0.1, 0.6],
        [0.6, 0.8, 0.5],
        [0.7, 0.4, 0.9]])
  b4=np.array([0.1, 0.2, 0.3])
  z4=np.dot(h3,W4)+b4
  y_hat=softmax(z4)

  # 回傳機率最高的類別
  return np.argmax(y_hat) + 1

In [ ]:
# 測試dnn函數
x=np.array([-1.0, 1.0, 2.0, 3.0, 4.0, 5.0])
y_hat = dnn(x)
print(f"dnn output: {y_hat}")

dnn output: 3


In [ ]:
# 建立 Gradio 介面
def predict(x1, x2, x3, x4, x5, x6):
  x = np.array([x1, x2, x3, x4, x5, x6])
  y_hat = dnn(x)
  return np.argmax(y_hat) + 1

inputs = [gr.Number(label=f"特徵{i}") for i in range(7)]
outputs = gr.Number(label="預測類別")

# 啟動gradio應用
interface = gr.Interface(fn=predict, inputs=inputs, outputs=outputs)

interface.launch()

/usr/local/lib/python3.11/dist-packages/gradio/utils.py:1024: UserWarning: Expected 6 arguments for function <function predict at 0x7acef1bdc4a0>, received 7.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/gradio/utils.py:1032: UserWarning: Expected maximum 6 arguments for function <function predict at 0x7acef1bdc4a0>, received 7.
  warnings.warn(


Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://8b9f5cd39588785f49.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
