<a href="https://colab.research.google.com/github/3B032007/2025_ML_hws/blob/main/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業2 模擬多隱藏層的全連接神經網路-批次學習

## 1、定義各個激發函數

In [ ]:
import numpy as np
# sigmoid激發函數
def sigmoid(x):
    return 1/(1+np.exp(-x))

# ReLU激發函數
def relu(x):
    return np.maximum(0, x)

#Softmax函數
def softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

## 2、輸入層批次輸入五筆資料(每筆6個神經元)

In [ ]:
batch_size=5

# 五筆資料 每筆6個神經元 = 5x6矩陣
X = np.array([[12.0, -7.0, 9.0, -3.0, 5.0, -10.0],
        [-14.0, 6.0, -8.0, 11.0, -2.0, 4.0],
        [3.0, -12.0, 7.0, -5.0, 10.0, 1.0],
        [-9.0, 14.0, -6.0, 8.0, -1.0, 13.0],
        [2.0, -11.0, 4.0, -15.0, 7.0, 1.0]])

# 真實結果
Y=np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0]])

## 3、第一層隱藏層5個神經元

In [ ]:
W1=np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
      [0.2, 0.3, 0.4, 0.5, 0.6],
      [0.3, 0.4, 0.5, 0.6, 0.7],
      [0.7, 0.6, 0.5, 0.4, 0.3],
      [0.6, 0.5, 0.4, 0.3, 0.2],
      [0.5, 0.4, 0.3, 0.2, 0.1]])
b1=np.array([0.1, 0.2, 0.3, 0.4, 0.5])

# 計算加權和z1及輸出量h1 激發函數使用ReLU
z1=np.dot(X,W1)+b1
h1=relu(z1)
print(h1)

[[ 0.   0.8  3.1  5.4  7.7]
 [ 6.   3.2  0.4  0.   0. ]
 [ 3.1  2.4  1.7  1.   0.3]
 [11.7  9.7  7.7  5.7  3.7]
 [ 0.   0.   0.   0.   0. ]]


## 4、第二層隱藏層4個神經元

In [6]:
W2=np.array([[0.1, 0.3, 0.5, 0.7],
      [0.2, 0.4, 0.6, 0.8],
      [0.3, 0.5, 0.7, 0.9],
      [0.4, 0.6, 0.8, 0.1],
      [0.5, 0.7, 0.9, 0.3]])
b2=np.array([0.1, 0.2, 0.3, 0.4])

# 計算加權和z2及輸出量h2 激發函數使用ReLU
z2=np.dot(h1,W2)+b2
h2=relu(z2)
print(h2)

[[ 7.2  10.7  14.2   6.68]
 [ 1.46  3.48  5.5   7.52]
 [ 1.95  3.75  5.55  6.21]
 [ 9.65 17.45 25.25 24.96]
 [ 0.1   0.2   0.3   0.4 ]]


## 5、第三層隱藏層4個神經元

In [7]:
W3=np.array([[0.7, 0.6, 0.4, 0.3],
      [0.4, 0.2, 0.1, 0.7],
      [0.8, 0.4, 0.3, 0.5],
      [0.1, 0.6, 0.9, 0.3]])
b3=np.array([0.1, 0.2, 0.3, 0.4])

# 計算加權和z3及輸出量h3 激發函數使用sigmoid
z3=np.dot(h2,W3)+b3
h3=sigmoid(z3)
print(h3)

[[1.         0.99999992 0.99999951 1.        ]
 [0.99953173 0.99979329 0.99993558 0.99974653]
 [0.99967325 0.99968606 0.99983493 0.99973829]
 [1.         1.         1.         1.        ]
 [0.62948311 0.65926039 0.6921095  0.69846522]]


## 6、輸出層3個神經元

In [9]:
W4=np.array([[0.3, 0.9, 0.4],
      [0.2, 0.1, 0.6],
      [0.6, 0.8, 0.5],
      [0.7, 0.4, 0.9]])
b4=np.array([0.1, 0.2, 0.3])

# 計算輸出結果 激發函數使用softmax
z4=np.dot(h3,W4)+b4
y_hat=softmax(z4)
print(y_hat)

[[0.04572992 0.07539589 0.10177382]
 [0.04571175 0.07535107 0.10171569]
 [0.04570968 0.07535355 0.10170903]
 [0.04572994 0.07539592 0.10177385]
 [0.02572959 0.03617209 0.04674822]]


## 7、利用cross_entropy_error衡量y_hat與y之間的誤差值

In [10]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

In [12]:
np.log(y_hat + 1e-7)

array([[-3.08500021, -2.58500116, -2.2850014 ],
       [-3.0853978 , -2.58559579, -2.28557277],
       [-3.08544294, -2.58556296, -2.28563823],
       [-3.08499989, -2.58500075, -2.2850011 ],
       [-3.66010983, -3.31946479, -3.06297702]])

In [14]:
Y*np.log(y_hat + 1e-7)

array([[-0.        , -0.        , -2.2850014 ],
       [-3.0853978 , -0.        , -0.        ],
       [-0.        , -2.58556296, -0.        ],
       [-0.        , -0.        , -2.2850011 ],
       [-3.66010983, -0.        , -0.        ]])

In [13]:
np.sum(Y * np.log(y_hat + 1e-7))

np.float64(-13.901073080644682)

In [15]:
-np.sum(Y * np.log(y_hat + 1e-7))

np.float64(13.901073080644682)

In [16]:
cross_entropy_error(y_hat, Y)

np.float64(2.7802146161289363)