<a href="https://colab.research.google.com/github/3B032007/2025_ML_hws/blob/main/hw6_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業6-2

In [2]:
import numpy as np

In [3]:
x1 = np.array([-1, 0, 1])
x2 = np.array([2, 1, 0])
x3 = np.array([0, 1, 2])

Wx = np.array([
    [1, 3, 5, 7],
    [-2, 4, -6, 8],
    [0, 4, 8, 12]
])# shape: (3, 4)

Wh = np.array([
    [-1, -2, 1, 2],
    [3, 1, 0, 2],
    [2, 1, -1, 0],
    [-3, 2, 0, -1]
])# shape: (4, 4)

b = np.array([0.1, 0.2, 0.3, 0.4])  # shape: (4,)

In [4]:
#RNN激活函數使用tanh

def tanh(x):
    return np.tanh(x)

h0 = np.zeros(4)

h1 = tanh(np.dot(x1, Wx) + np.dot(h0, Wh) + b)
print("h1:", h1)

h2 = tanh(np.dot(x2, Wx) + np.dot(h1, Wh) + b)
print("h2:", h2)

h3 = tanh(np.dot(x3, Wx) + np.dot(h2, Wh) + b)
print("h3:", h3)


h1: [-0.71629787  0.83365461  0.99728296  0.9999592 ]
h2: [0.98056188 1.         0.98872699 1.        ]
h3: [-0.7178078  1.         1.         1.       ]


# 作業6-3

In [5]:
import numpy as np

In [6]:
x1 = np.array([1, 2, 3])
x2 = np.array([0, 1, -1])
x3 = np.array([-2, 0, 2])

Wx = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 1, 11, 12]
])
Wh = np.array([
    [1, 0, -1, 0],
    [0, 1, 0, -1],
    [-1, 0, 1, 0],
    [0, -1, 0, 1]
])
b = np.array([0.01, 0.02, 0.03, 0.04])

In [7]:
def tanh(x):
    return np.tanh(x)

h0 = np.zeros(4)

h1 = tanh(np.dot(x1, Wx) + np.dot(h0, Wh) + b)
h2 = tanh(np.dot(x2, Wx) + np.dot(h1, Wh) + b)
h3 = tanh(np.dot(x3, Wx) + np.dot(h2, Wh) + b)

In [8]:
S3 = np.array([2, 5, 3, 1])

e1 = np.dot(S3, h1)
e2 = np.dot(S3, h2)
e3 = np.dot(S3, h3)

print("注意力強度e:", [e1, e2, e3])

注意力強度e: [np.float64(10.999999999999982), np.float64(-0.996204670896435), np.float64(6.0959193487892565)]


In [9]:
def softmax(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

alpha = softmax(np.array([e1, e2, e3]))
alpha1, alpha2, alpha3 = alpha
print("alpha1, alpha2, alpha3:", alpha1, alpha2, alpha3)

alpha1, alpha2, alpha3: 0.9926322608425214 6.122134878574959e-06 0.00736161702260013


In [10]:
c3 = alpha1 * h1 + alpha2 * h2 + alpha3 * h3
print("c3:", c3)

c3: [0.99998776 0.99277961 0.99998776 0.99998776]


# 作業6-4

In [11]:
x1 = np.array([1, 2, 3])
x2 = np.array([0, 1, -1])
x3 = np.array([-2, 0, 2])

X = np.array([x1, x2, x3])

In [12]:
Wq = np.array([
    [1, 0 ,0],
    [0, 1 ,2],
    [0, 0 ,1]])

Wk = np.array([
    [0, 2 ,1],
    [0, 1 ,1],
    [1, 0 ,2]])

Wv = np.array([
    [2, 1 ,1],
    [0, 3 ,3],
    [2, 0 ,1]])

In [13]:
Q = np.dot(X, Wq)
K = np.dot(X, Wk)
V = np.dot(X, Wv)

print("Q:\n", Q)
print("K:\n", K)
print("V:\n", V)

Q:
 [[ 1  2  7]
 [ 0  1  1]
 [-2  0  2]]
K:
 [[ 3  4  9]
 [-1  1 -1]
 [ 2 -4  2]]
V:
 [[ 8  7 10]
 [-2  3  2]
 [ 0 -2  0]]


In [14]:
def attention(Q, K, V):
  dk = K.shape[-1]
  scores = np.dot(Q, K.T) / np.sqrt(dk)
  attention_weights = softmax(scores)
  output = np.dot(attention_weights, V)
  return output, attention_weights

self_attention_output, attention_weights = attention(Q, K, V)
print("Self Attention Output:\n", self_attention_output)
print("Attention Weights:\n", attention_weights)

Self Attention Output:
 [[8.00000000e+00 7.00000000e+00 1.00000000e+01]
 [4.05404035e-15 3.54843373e-15 5.06880488e-15]
 [2.27562850e-15 1.99194154e-15 2.84579006e-15]]
Attention Weights:
 [[1.00000000e+00 8.72563651e-21 2.82590542e-17]
 [5.06824735e-16 2.78764415e-19 8.78531345e-20]
 [2.84523253e-16 2.78764415e-19 2.78764415e-19]]


In [19]:
# 驗證
q1 = np.dot(x1, Wq)
k1 = np.dot(x1, Wk)
v1 = np.dot(x1, Wv)

print("q1:", q1)
print("k1:", k1)
print("v1:", v1)

print("\nQ[0] =", Q[0])
print("K[0] =", K[0])
print("V[0] =", V[0])

q1: [1 2 7]
k1: [3 4 9]
v1: [ 8  7 10]

Q[0] = [1 2 7]
K[0] = [3 4 9]
V[0] = [ 8  7 10]
